# MD013/line-length - Line length
MD013:
  # Number of characters
  line_length: 120

# MD024/no-duplicate-heading/no-duplicate-header - Multiple headings with the same content
MD024:
  siblings_only: true
